{{- if .Values.continuum.featureCheminformatics.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "continuum-feature-cheminformatics.fullname" . }}-cache
  labels:
    {{- include "continuum-feature-cheminformatics.componentLabels" (dict "context" $ "component" "feature-cheminformatics" "extra" .Values.continuum.featureCheminformatics.labels.pvc) | nindent 4 }}
  {{- with (include "continuum-feature-cheminformatics.componentAnnotations" (dict "context" $ "extra" .Values.continuum.featureCheminformatics.annotations.pvc)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.continuum.cacheStorage.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.continuum.cacheStorage.storageClassName }}
  storageClassName: {{ .Values.continuum.cacheStorage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.continuum.cacheStorage.size | default "5Gi" }}
{{- end }}
